### ISSUE TITLE
SRV record's failed

### ISSUE THREAD

**Issue by DaBeOps** [gheesh/ansible-ovh-dns#13]
Hi,

First, thank you for sharing this.

I am using your module which works well so far for records type A, AAAA.

Now I am facing a different need which is using SRV type and I am getting errors:

```yaml
item:
  domain: xxxxx.fr
  name: _node-exporter._tcp
  state: present
  type: SRV
  value: 0 8100 server.bonnel.xxxxx.fr
module_stderr: |-
  Traceback (most recent call last):
    File "<stdin>", line 102, in <module>
    File "<stdin>", line 94, in _ansiballz_main
    File "<stdin>", line 40, in invoke_module
    File "/usr/lib/python3.6/runpy.py", line 205, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
      mod_name, mod_spec, pkg_name, script_name)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/tmp/ansible_ovh_dns_payload_xvfetxji/ansible_ovh_dns_payload.zip/ansible/modules/ovh_dns.py", line 314, in <module>
    File "/tmp/ansible_ovh_dns_payload_xvfetxji/ansible_ovh_dns_payload.zip/ansible/modules/ovh_dns.py", line 297, in main
    File "/usr/local/lib/python3.6/dist-packages/ovh/client.py", line 377, in post
      return self.call('POST', _target, kwargs, _need_auth)
    File "/usr/local/lib/python3.6/dist-packages/ovh/client.py", line 446, in call
      response=result)
  ovh.exceptions.BadParametersError: Destination invalide
  OVH-Query-ID: EU.ext-2.5f904c1a.14365.60c9f130-f42e-432c-bb08-c9cc2c91b895
```
Have you ever encountered this kind of problem?

**Comment by alexandrelb** [comment]
Hi,

I have same error on 'MX' record. 'A' record works.
Can you explain how do you solve this ?
Maybe your solution can guide me to solve my issue.

thanks
